language: go
dist: xenial

env:
  global:
    - GO111MODULE=on

matrix:
  include:
    - go: "1.11.x"
    - go: "1.12.x"
    - go: master
    - os: osx
      go: "1.11.x"
    - os: osx
      go: "1.12.x"
    - os: osx
      go: master
