name: Go
on:
  push:
  pull_request:
  schedule:
    - cron: "0 2 * * *"

jobs:

  build:
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-latest, windows-latest, macos-latest]
    name: Build
    runs-on: ${{ matrix.os }}
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      env:
        GO111MODULE: on
        GOPROXY: https://proxy.golang.org,direct
      run: go build -v .
    
    - name: Tests
      run: go test -v ./...
